/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRaschetyRouteImport } from './routes/services_.raschety'
import { Route as ServicesProizvodstvoRouteImport } from './routes/services_.proizvodstvo'
import { Route as ServicesKonstruirovanieRouteImport } from './routes/services_.konstruirovanie'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRaschetyRoute = ServicesRaschetyRouteImport.update({
  id: '/services_/raschety',
  path: '/services/raschety',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProizvodstvoRoute = ServicesProizvodstvoRouteImport.update({
  id: '/services_/proizvodstvo',
  path: '/services/proizvodstvo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesKonstruirovanieRoute = ServicesKonstruirovanieRouteImport.update({
  id: '/services_/konstruirovanie',
  path: '/services/konstruirovanie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/services/konstruirovanie': typeof ServicesKonstruirovanieRoute
  '/services/proizvodstvo': typeof ServicesProizvodstvoRoute
  '/services/raschety': typeof ServicesRaschetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/services/konstruirovanie': typeof ServicesKonstruirovanieRoute
  '/services/proizvodstvo': typeof ServicesProizvodstvoRoute
  '/services/raschety': typeof ServicesRaschetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/services_/konstruirovanie': typeof ServicesKonstruirovanieRoute
  '/services_/proizvodstvo': typeof ServicesProizvodstvoRoute
  '/services_/raschety': typeof ServicesRaschetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/services/konstruirovanie'
    | '/services/proizvodstvo'
    | '/services/raschety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/services/konstruirovanie'
    | '/services/proizvodstvo'
    | '/services/raschety'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/services_/konstruirovanie'
    | '/services_/proizvodstvo'
    | '/services_/raschety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  ServicesKonstruirovanieRoute: typeof ServicesKonstruirovanieRoute
  ServicesProizvodstvoRoute: typeof ServicesProizvodstvoRoute
  ServicesRaschetyRoute: typeof ServicesRaschetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/raschety': {
      id: '/services_/raschety'
      path: '/services/raschety'
      fullPath: '/services/raschety'
      preLoaderRoute: typeof ServicesRaschetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/proizvodstvo': {
      id: '/services_/proizvodstvo'
      path: '/services/proizvodstvo'
      fullPath: '/services/proizvodstvo'
      preLoaderRoute: typeof ServicesProizvodstvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/konstruirovanie': {
      id: '/services_/konstruirovanie'
      path: '/services/konstruirovanie'
      fullPath: '/services/konstruirovanie'
      preLoaderRoute: typeof ServicesKonstruirovanieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  ServicesKonstruirovanieRoute: ServicesKonstruirovanieRoute,
  ServicesProizvodstvoRoute: ServicesProizvodstvoRoute,
  ServicesRaschetyRoute: ServicesRaschetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
